name: 'Discrepancy Report'
description: 'Use this if you have Discrepancy Testing turned on and have a discrepancy to report'
title: '[Discrepancy]'
body:
  - type: input
    attributes:
      label: 'Mission ID'
  - type: textarea
    attributes:
      label: 'Upload the saved variable file here'
